---
kind: pkgfile.Build
spec:
  targets:
    - toolchain
    - toolchain-musl
  reproducibleTargetName: toolchain
---
kind: common.Renovate
spec:
  packageRules:
    - matchPackageNames:
        - git://sourceware.org/git/binutils-gdb.git
      versioning: 'regex:^(?<major>\d+)_(?<minor>\d+)_?(?<patch>\d+)?$'
    - matchPackageNames:
        - git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
      allowedVersions: "<= 6.17"
